brew "bat"
brew "btop"
brew "cmake"
brew "coreutils"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gcc"
brew "git"
brew "lazydocker"
brew "lazygit"
brew "libyaml"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "starship"
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "tmux"
brew "tree-sitter"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"

cask "1password"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-noto-sans-mono-cjk-sc"
cask "ghostty"
cask "zed"

cask "orbstack" unless `whoami`.strip.include?(".")
