# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncation_length = 3

[cmd_duration]
min_time = 3000
format = "took [$duration]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[ruby]
detect_files = ["Gemfile", ".ruby-version"]
format = "[$symbol($version)]($style) "

[python]
detect_files = ["pyproject.toml", "requirements.txt", ".python-version"]
format = "[$symbol($version)]($style) "

[hostname]
disabled = true

[username]
disabled = true

[docker_context]
disabled = true
